FROM metabase/metabase:latest

# Usa curl para baixar o driver, que é mais robusto
# RUN curl -L -o /plugins/h2.metabase-driver.jar https://github.com/metabase/metabase-community-drivers/releases/download/h2-1.1.0/h2.metabase-driver.jar