services:
  dimp-processor:
    image: saulomed/dimp-processor:latest
    container_name: dimp-processor
    ports:
      - "8080:8080"
    volumes:
      - ./dimp-files:/data
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dimpdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  metabase:
    build: ./metabase
    container_name: metabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=dimpdb
      - MB_DB_PORT=5432
      - MB_DB_USER=user
      - MB_DB_PASS=password
      - MB_DB_HOST=postgres

volumes:
  postgres-data:
